### ISSUE TITLE
issue: ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by bansal** [denoland/image-resizing-api#2]
I am getting this error:
```sh
gcp-us-east4 isolate start time: 111.91 ms
gcp-us-east4 Listening on http://localhost:80/
gcp-asia-south1 ReferenceError: __dirname is not defined
    at https://deno.land/x/imagemagick_deno@0.0.14/src/wasm/magick_native.js:9:1767
    at https://deno.land/x/imagemagick_deno@0.0.14/src/image-magick.ts:26:7
    at new Promise (<anonymous>)
    at new ImageMagick (https://deno.land/x/imagemagick_deno@0.0.14/src/image-magick.ts:20:19)
    at Function._create (https://deno.land/x/imagemagick_deno@0.0.14/src/image-magick.ts:38:39)
    at https://deno.land/x/imagemagick_deno@0.0.14/src/image-magick.ts:239:30
```

**Comment by tedsecretsource** [comment]
Change the wasm import to (update the version):
```js
import {
    ImageMagick,
    initializeImageMagick,
    MagickGeometry,
} from "https://deno.land/x/imagemagick_deno@0.0.31/mod.ts";
```

But then you'll have a new error about not being able to read magick.wasm (invalid URL).

Good luck!
